"use client"
import { usePathname, useRouter } from "next/navigation";
import { useCallback, useEffect, useRef, useState } from "react";
import { useRecoilState } from "recoil";
import { commonLayoutModeStateAtom } from "../common-layout/common-layout.atom";
import styles from "./side-bar.component.module.scss";
import { ISideBar } from "./side-bar.interface";
import anime from 'animejs/lib/anime.es.js';

const SideBar = (props: ISideBar.Props) => {
  const sideBarElementRef = useRef<HTMLDivElement>(null);
  const [commonLayoutModeState, setCommonLayoutModeState] = useRecoilState(commonLayoutModeStateAtom);
  const [isActiveTransition, setIsActiveTransition] = useState(false);

  const router = useRouter();
  const pathname = usePathname();
  const [menuItems, setMenuItems] = useState<ISideBar.MenuItem[]>([
    { menuName: 'd3-001-adder', menuLink: '/d3-example/d3-001-adder' },
    { menuName: 'd3-002-delaunay', menuLink: '/d3-example/d3-002-delaunay' },
    { menuName: 'd3-003-format-specifier', menuLink: '/d3-example/d3-003-format-specifier' },
    { menuName: 'd3-004-intern-map', menuLink: '/d3-example/d3-004-intern-map' },
    { menuName: 'd3-005-intern-set', menuLink: '/d3-example/d3-005-intern-set' },
    { menuName: 'd3-006-voronoi', menuLink: '/d3-example/d3-006-voronoi' },
    { menuName: 'd3-007-zoom-transform', menuLink: '/d3-example/d3-007-zoom-transform' },
    { menuName: 'd3-008-active', menuLink: '/d3-example/d3-008-active' },
    { menuName: 'd3-009-arc', menuLink: '/d3-example/d3-009-arc' },
    { menuName: 'd3-010-area', menuLink: '/d3-example/d3-010-area' },
    { menuName: 'd3-011-areaRadial', menuLink: '/d3-example/d3-011-areaRadial' },
    { menuName: 'd3-012-ascending', menuLink: '/d3-example/d3-012-ascending' },
    { menuName: 'd3-013-autoType', menuLink: '/d3-example/d3-013-autoType' },
    { menuName: 'd3-014-axisBottom', menuLink: '/d3-example/d3-014-axisBottom' },
    { menuName: 'd3-015-axisLeft', menuLink: '/d3-example/d3-015-axisLeft' },
    { menuName: 'd3-016-axisRight', menuLink: '/d3-example/d3-016-axisRight' },
    { menuName: 'd3-017-axisTop', menuLink: '/d3-example/d3-017-axisTop' },
    { menuName: 'd3-018-bin', menuLink: '/d3-example/d3-018-bin' },
    { menuName: 'd3-019-bisect', menuLink: '/d3-example/d3-019-bisect' },
    { menuName: 'd3-020-bisectCenter', menuLink: '/d3-example/d3-020-bisectCenter' },
    { menuName: 'd3-021-bisectLeft', menuLink: '/d3-example/d3-021-bisectLeft' },
    { menuName: 'd3-022-bisectRight', menuLink: '/d3-example/d3-022-bisectRight' },
    { menuName: 'd3-023-bisector', menuLink: '/d3-example/d3-023-bisector' },
    { menuName: 'd3-024-blob', menuLink: '/d3-example/d3-024-blob' },
    { menuName: 'd3-025-brush', menuLink: '/d3-example/d3-025-brush' },
    { menuName: 'd3-026-brushSelection', menuLink: '/d3-example/d3-026-brushSelection' },
    { menuName: 'd3-027-brushX', menuLink: '/d3-example/d3-027-brushX' },
    { menuName: 'd3-028-brushY', menuLink: '/d3-example/d3-028-brushY' },
    { menuName: 'd3-029-buffer', menuLink: '/d3-example/d3-029-buffer' },
    { menuName: 'd3-030-chord', menuLink: '/d3-example/d3-030-chord' },
    { menuName: 'd3-031-chordDirected', menuLink: '/d3-example/d3-031-chordDirected' },
    { menuName: 'd3-032-chordTranspose', menuLink: '/d3-example/d3-032-chordTranspose' },
    { menuName: 'd3-033-cluster', menuLink: '/d3-example/d3-033-cluster' },
    { menuName: 'd3-034-color', menuLink: '/d3-example/d3-034-color' },
    { menuName: 'd3-035-contourDensity', menuLink: '/d3-example/d3-035-contourDensity' },
    { menuName: 'd3-036-contours', menuLink: '/d3-example/d3-036-contours' },
    { menuName: 'd3-037-count', menuLink: '/d3-example/d3-037-count' },
    { menuName: 'd3-038-create', menuLink: '/d3-example/d3-038-create' },
    { menuName: 'd3-039-creator', menuLink: '/d3-example/d3-039-creator' },
    { menuName: 'd3-040-cross', menuLink: '/d3-example/d3-040-cross' },
    { menuName: 'd3-041-csv', menuLink: '/d3-example/d3-041-csv' },
    { menuName: 'd3-042-csvFormat', menuLink: '/d3-example/d3-042-csvFormat' },
    { menuName: 'd3-043-csvFormatBody', menuLink: '/d3-example/d3-043-csvFormatBody' },
    { menuName: 'd3-044-csvFormatRow', menuLink: '/d3-example/d3-044-csvFormatRow' },
    { menuName: 'd3-045-csvFormatRows', menuLink: '/d3-example/d3-045-csvFormatRows' },
    { menuName: 'd3-046-csvFormatValue', menuLink: '/d3-example/d3-046-csvFormatValue' },
    { menuName: 'd3-047-csvParse', menuLink: '/d3-example/d3-047-csvParse' },
    { menuName: 'd3-048-csvParseRows', menuLink: '/d3-example/d3-048-csvParseRows' },
    { menuName: 'd3-049-cubehelix', menuLink: '/d3-example/d3-049-cubehelix' },
    { menuName: 'd3-050-cumsum', menuLink: '/d3-example/d3-050-cumsum' },
    { menuName: 'd3-051-curveBasis', menuLink: '/d3-example/d3-051-curveBasis' },
    { menuName: 'd3-052-curveBasisClosed', menuLink: '/d3-example/d3-052-curveBasisClosed' },
    { menuName: 'd3-053-curveBasisOpen', menuLink: '/d3-example/d3-053-curveBasisOpen' },
    { menuName: 'd3-054-curveBumpX', menuLink: '/d3-example/d3-054-curveBumpX' },
    { menuName: 'd3-055-curveBumpY', menuLink: '/d3-example/d3-055-curveBumpY' },
    { menuName: 'd3-056-curveBundle', menuLink: '/d3-example/d3-056-curveBundle' },
    { menuName: 'd3-057-curveCardinal', menuLink: '/d3-example/d3-057-curveCardinal' },
    { menuName: 'd3-058-curveCardinalClosed', menuLink: '/d3-example/d3-058-curveCardinalClosed' },
    { menuName: 'd3-059-curveCardinalOpen', menuLink: '/d3-example/d3-059-curveCardinalOpen' },
    { menuName: 'd3-060-curveCatmullRom', menuLink: '/d3-example/d3-060-curveCatmullRom' },
    { menuName: 'd3-061-curveCatmullRomClosed', menuLink: '/d3-example/d3-061-curveCatmullRomClosed' },
    { menuName: 'd3-062-curveCatmullRomOpen', menuLink: '/d3-example/d3-062-curveCatmullRomOpen' },
    { menuName: 'd3-063-curveLinear', menuLink: '/d3-example/d3-063-curveLinear' },
    { menuName: 'd3-064-curveLinearClosed', menuLink: '/d3-example/d3-064-curveLinearClosed' },
    { menuName: 'd3-065-curveMonotoneX', menuLink: '/d3-example/d3-065-curveMonotoneX' },
    { menuName: 'd3-066-curveMonotoneY', menuLink: '/d3-example/d3-066-curveMonotoneY' },
    { menuName: 'd3-067-curveNatural', menuLink: '/d3-example/d3-067-curveNatural' },
    { menuName: 'd3-068-curveStep', menuLink: '/d3-example/d3-068-curveStep' },
    { menuName: 'd3-069-curveStepAfter', menuLink: '/d3-example/d3-069-curveStepAfter' },
    { menuName: 'd3-070-curveStepBefore', menuLink: '/d3-example/d3-070-curveStepBefore' },
    { menuName: 'd3-071-descending', menuLink: '/d3-example/d3-071-descending' },
    { menuName: 'd3-072-deviation', menuLink: '/d3-example/d3-072-deviation' },
    { menuName: 'd3-073-difference', menuLink: '/d3-example/d3-073-difference' },
    { menuName: 'd3-074-disjoint', menuLink: '/d3-example/d3-074-disjoint' },
    { menuName: 'd3-075-dispatch', menuLink: '/d3-example/d3-075-dispatch' },
    { menuName: 'd3-076-drag', menuLink: '/d3-example/d3-076-drag' },
    { menuName: 'd3-077-dragDisable', menuLink: '/d3-example/d3-077-dragDisable' },
    { menuName: 'd3-078-dragEnable', menuLink: '/d3-example/d3-078-dragEnable' },
    { menuName: 'd3-079-dsv', menuLink: '/d3-example/d3-079-dsv' },
    { menuName: 'd3-080-dsvFormat', menuLink: '/d3-example/d3-080-dsvFormat' },
    { menuName: 'd3-081-easeBack', menuLink: '/d3-example/d3-081-easeBack' },
    { menuName: 'd3-082-easeBackIn', menuLink: '/d3-example/d3-082-easeBackIn' },
    { menuName: 'd3-083-easeBackInOut', menuLink: '/d3-example/d3-083-easeBackInOut' },
    { menuName: 'd3-084-easeBackOut', menuLink: '/d3-example/d3-084-easeBackOut' },
    { menuName: 'd3-085-easeBounce', menuLink: '/d3-example/d3-085-easeBounce' },
    { menuName: 'd3-086-easeBounceIn', menuLink: '/d3-example/d3-086-easeBounceIn' },
    { menuName: 'd3-087-easeBounceInOut', menuLink: '/d3-example/d3-087-easeBounceInOut' },
    { menuName: 'd3-088-easeBounceOut', menuLink: '/d3-example/d3-088-easeBounceOut' },
    { menuName: 'd3-089-easeCircle', menuLink: '/d3-example/d3-089-easeCircle' },
    { menuName: 'd3-090-easeCircleIn', menuLink: '/d3-example/d3-090-easeCircleIn' },
    { menuName: 'd3-091-easeCircleInOut', menuLink: '/d3-example/d3-091-easeCircleInOut' },
    { menuName: 'd3-092-easeCircleOut', menuLink: '/d3-example/d3-092-easeCircleOut' },
    { menuName: 'd3-093-easeCubic', menuLink: '/d3-example/d3-093-easeCubic' },
    { menuName: 'd3-094-easeCubicIn', menuLink: '/d3-example/d3-094-easeCubicIn' },
    { menuName: 'd3-095-easeCubicInOut', menuLink: '/d3-example/d3-095-easeCubicInOut' },
    { menuName: 'd3-096-easeCubicOut', menuLink: '/d3-example/d3-096-easeCubicOut' },
    { menuName: 'd3-097-easeElastic', menuLink: '/d3-example/d3-097-easeElastic' },
    { menuName: 'd3-098-easeElasticIn', menuLink: '/d3-example/d3-098-easeElasticIn' },
    { menuName: 'd3-099-easeElasticInOut', menuLink: '/d3-example/d3-099-easeElasticInOut' },
    { menuName: 'd3-100-easeElasticOut', menuLink: '/d3-example/d3-100-easeElasticOut' },
    { menuName: 'd3-101-easeExp', menuLink: '/d3-example/d3-101-easeExp' },
    { menuName: 'd3-102-easeExpIn', menuLink: '/d3-example/d3-102-easeExpIn' },
    { menuName: 'd3-103-easeExpInOut', menuLink: '/d3-example/d3-103-easeExpInOut' },
    { menuName: 'd3-104-easeExpOut', menuLink: '/d3-example/d3-104-easeExpOut' },
    { menuName: 'd3-105-easeLinear', menuLink: '/d3-example/d3-105-easeLinear' },
    { menuName: 'd3-106-easePoly', menuLink: '/d3-example/d3-106-easePoly' },
    { menuName: 'd3-107-easePolyIn', menuLink: '/d3-example/d3-107-easePolyIn' },
    { menuName: 'd3-108-easePolyInOut', menuLink: '/d3-example/d3-108-easePolyInOut' },
    { menuName: 'd3-109-easePolyOut', menuLink: '/d3-example/d3-109-easePolyOut' },
    { menuName: 'd3-110-easeQuad', menuLink: '/d3-example/d3-110-easeQuad' },
    { menuName: 'd3-111-easeQuadIn', menuLink: '/d3-example/d3-111-easeQuadIn' },
    { menuName: 'd3-112-easeQuadInOut', menuLink: '/d3-example/d3-112-easeQuadInOut' },
    { menuName: 'd3-113-easeQuadOut', menuLink: '/d3-example/d3-113-easeQuadOut' },
    { menuName: 'd3-114-easeSin', menuLink: '/d3-example/d3-114-easeSin' },
    { menuName: 'd3-115-easeSinIn', menuLink: '/d3-example/d3-115-easeSinIn' },
    { menuName: 'd3-116-easeSinInOut', menuLink: '/d3-example/d3-116-easeSinInOut' },
    { menuName: 'd3-117-easeSinOut', menuLink: '/d3-example/d3-117-easeSinOut' },
    { menuName: 'd3-118-every', menuLink: '/d3-example/d3-118-every' },
    { menuName: 'd3-119-extent', menuLink: '/d3-example/d3-119-extent' },
    { menuName: 'd3-120-fcumsum', menuLink: '/d3-example/d3-120-fcumsum' },
    { menuName: 'd3-121-filter', menuLink: '/d3-example/d3-121-filter' },
    { menuName: 'd3-122-flatGroup', menuLink: '/d3-example/d3-122-flatGroup' },
    { menuName: 'd3-123-flatRollup', menuLink: '/d3-example/d3-123-flatRollup' },
    { menuName: 'd3-124-forceCenter', menuLink: '/d3-example/d3-124-forceCenter' },
    { menuName: 'd3-125-forceCollide', menuLink: '/d3-example/d3-125-forceCollide' },
    { menuName: 'd3-126-forceLink', menuLink: '/d3-example/d3-126-forceLink' },
    { menuName: 'd3-127-forceManyBody', menuLink: '/d3-example/d3-127-forceManyBody' },
    { menuName: 'd3-128-forceRadial', menuLink: '/d3-example/d3-128-forceRadial' },
    { menuName: 'd3-129-forceSimulation', menuLink: '/d3-example/d3-129-forceSimulation' },
    { menuName: 'd3-130-forceX', menuLink: '/d3-example/d3-130-forceX' },
    { menuName: 'd3-131-forceY', menuLink: '/d3-example/d3-131-forceY' },
    { menuName: 'd3-132-format', menuLink: '/d3-example/d3-132-format' },
    { menuName: 'd3-133-formatDefaultLocale', menuLink: '/d3-example/d3-133-formatDefaultLocale' },
    { menuName: 'd3-134-formatLocale', menuLink: '/d3-example/d3-134-formatLocale' },
    { menuName: 'd3-135-formatPrefix', menuLink: '/d3-example/d3-135-formatPrefix' },
    { menuName: 'd3-136-formatSpecifier', menuLink: '/d3-example/d3-136-formatSpecifier' },
    { menuName: 'd3-137-fsum', menuLink: '/d3-example/d3-137-fsum' },
    { menuName: 'd3-138-geoAlbers', menuLink: '/d3-example/d3-138-geoAlbers' },
    { menuName: 'd3-139-geoAlbersUsa', menuLink: '/d3-example/d3-139-geoAlbersUsa' },
    { menuName: 'd3-140-geoArea', menuLink: '/d3-example/d3-140-geoArea' },
    { menuName: 'd3-141-geoAzimuthalEqualArea', menuLink: '/d3-example/d3-141-geoAzimuthalEqualArea' },
    { menuName: 'd3-142-geoAzimuthalEqualAreaRaw', menuLink: '/d3-example/d3-142-geoAzimuthalEqualAreaRaw' },
    { menuName: 'd3-143-geoAzimuthalEquidistant', menuLink: '/d3-example/d3-143-geoAzimuthalEquidistant' },
    { menuName: 'd3-144-geoAzimuthalEquidistantRaw', menuLink: '/d3-example/d3-144-geoAzimuthalEquidistantRaw' },
    { menuName: 'd3-145-geoBounds', menuLink: '/d3-example/d3-145-geoBounds' },
    { menuName: 'd3-146-geoCentroid', menuLink: '/d3-example/d3-146-geoCentroid' },
    { menuName: 'd3-147-geoCircle', menuLink: '/d3-example/d3-147-geoCircle' },
    { menuName: 'd3-148-geoClipAntimeridian', menuLink: '/d3-example/d3-148-geoClipAntimeridian' },
    { menuName: 'd3-149-geoClipCircle', menuLink: '/d3-example/d3-149-geoClipCircle' },
    { menuName: 'd3-150-geoClipRectangle', menuLink: '/d3-example/d3-150-geoClipRectangle' },
    { menuName: 'd3-151-geoConicConformal', menuLink: '/d3-example/d3-151-geoConicConformal' },
    { menuName: 'd3-152-geoConicConformalRaw', menuLink: '/d3-example/d3-152-geoConicConformalRaw' },
    { menuName: 'd3-153-geoConicEqualArea', menuLink: '/d3-example/d3-153-geoConicEqualArea' },
    { menuName: 'd3-154-geoConicEqualAreaRaw', menuLink: '/d3-example/d3-154-geoConicEqualAreaRaw' },
    { menuName: 'd3-155-geoConicEquidistant', menuLink: '/d3-example/d3-155-geoConicEquidistant' },
    { menuName: 'd3-156-geoConicEquidistantRaw', menuLink: '/d3-example/d3-156-geoConicEquidistantRaw' },
    { menuName: 'd3-157-geoContains', menuLink: '/d3-example/d3-157-geoContains' },
    { menuName: 'd3-158-geoDistance', menuLink: '/d3-example/d3-158-geoDistance' },
    { menuName: 'd3-159-geoEqualEarth', menuLink: '/d3-example/d3-159-geoEqualEarth' },
    { menuName: 'd3-160-geoEqualEarthRaw', menuLink: '/d3-example/d3-160-geoEqualEarthRaw' },
    { menuName: 'd3-161-geoEquirectangular', menuLink: '/d3-example/d3-161-geoEquirectangular' },
    { menuName: 'd3-162-geoEquirectangularRaw', menuLink: '/d3-example/d3-162-geoEquirectangularRaw' },
    { menuName: 'd3-163-geoGnomonic', menuLink: '/d3-example/d3-163-geoGnomonic' },
    { menuName: 'd3-164-geoGnomonicRaw', menuLink: '/d3-example/d3-164-geoGnomonicRaw' },
    { menuName: 'd3-165-geoGraticule', menuLink: '/d3-example/d3-165-geoGraticule' },
    { menuName: 'd3-166-geoGraticule10', menuLink: '/d3-example/d3-166-geoGraticule10' },
    { menuName: 'd3-167-geoIdentity', menuLink: '/d3-example/d3-167-geoIdentity' },
    { menuName: 'd3-168-geoInterpolate', menuLink: '/d3-example/d3-168-geoInterpolate' },
    { menuName: 'd3-169-geoLength', menuLink: '/d3-example/d3-169-geoLength' },
    { menuName: 'd3-170-geoMercator', menuLink: '/d3-example/d3-170-geoMercator' },
    { menuName: 'd3-171-geoMercatorRaw', menuLink: '/d3-example/d3-171-geoMercatorRaw' },
    { menuName: 'd3-172-geoNaturalEarth1', menuLink: '/d3-example/d3-172-geoNaturalEarth1' },
    { menuName: 'd3-173-geoNaturalEarth1Raw', menuLink: '/d3-example/d3-173-geoNaturalEarth1Raw' },
    { menuName: 'd3-174-geoOrthographic', menuLink: '/d3-example/d3-174-geoOrthographic' },
    { menuName: 'd3-175-geoOrthographicRaw', menuLink: '/d3-example/d3-175-geoOrthographicRaw' },
    { menuName: 'd3-176-geoPath', menuLink: '/d3-example/d3-176-geoPath' },
    { menuName: 'd3-177-geoProjection', menuLink: '/d3-example/d3-177-geoProjection' },
    { menuName: 'd3-178-geoProjectionMutator', menuLink: '/d3-example/d3-178-geoProjectionMutator' },
    { menuName: 'd3-179-geoRotation', menuLink: '/d3-example/d3-179-geoRotation' },
    { menuName: 'd3-180-geoStereographic', menuLink: '/d3-example/d3-180-geoStereographic' },
    { menuName: 'd3-181-geoStereographicRaw', menuLink: '/d3-example/d3-181-geoStereographicRaw' },
    { menuName: 'd3-182-geoStream', menuLink: '/d3-example/d3-182-geoStream' },
    { menuName: 'd3-183-geoTransform', menuLink: '/d3-example/d3-183-geoTransform' },
    { menuName: 'd3-184-geoTransverseMercator', menuLink: '/d3-example/d3-184-geoTransverseMercator' },
    { menuName: 'd3-185-geoTransverseMercatorRaw', menuLink: '/d3-example/d3-185-geoTransverseMercatorRaw' },
    { menuName: 'd3-186-gray', menuLink: '/d3-example/d3-186-gray' },
    { menuName: 'd3-187-greatest', menuLink: '/d3-example/d3-187-greatest' },
    { menuName: 'd3-188-greatestIndex', menuLink: '/d3-example/d3-188-greatestIndex' },
    { menuName: 'd3-189-group', menuLink: '/d3-example/d3-189-group' },
    { menuName: 'd3-190-groupSort', menuLink: '/d3-example/d3-190-groupSort' },
    { menuName: 'd3-191-groups', menuLink: '/d3-example/d3-191-groups' },
    { menuName: 'd3-192-hcl', menuLink: '/d3-example/d3-192-hcl' },
    { menuName: 'd3-193-hierarchy', menuLink: '/d3-example/d3-193-hierarchy' },
    { menuName: 'd3-194-hsl', menuLink: '/d3-example/d3-194-hsl' },
    { menuName: 'd3-195-html', menuLink: '/d3-example/d3-195-html' },
    { menuName: 'd3-196-image', menuLink: '/d3-example/d3-196-image' },
    { menuName: 'd3-197-index', menuLink: '/d3-example/d3-197-index' },
    { menuName: 'd3-198-indexes', menuLink: '/d3-example/d3-198-indexes' },
    { menuName: 'd3-199-interpolate', menuLink: '/d3-example/d3-199-interpolate' },
    { menuName: 'd3-200-interpolateArray', menuLink: '/d3-example/d3-200-interpolateArray' },
    { menuName: 'd3-201-interpolateBasis', menuLink: '/d3-example/d3-201-interpolateBasis' },
    { menuName: 'd3-202-interpolateBasisClosed', menuLink: '/d3-example/d3-202-interpolateBasisClosed' },
    { menuName: 'd3-203-interpolateBlues', menuLink: '/d3-example/d3-203-interpolateBlues' },
    { menuName: 'd3-204-interpolateBrBG', menuLink: '/d3-example/d3-204-interpolateBrBG' },
    { menuName: 'd3-205-interpolateBuGn', menuLink: '/d3-example/d3-205-interpolateBuGn' },
    { menuName: 'd3-206-interpolateBuPu', menuLink: '/d3-example/d3-206-interpolateBuPu' },
    { menuName: 'd3-207-interpolateCividis', menuLink: '/d3-example/d3-207-interpolateCividis' },
    { menuName: 'd3-208-interpolateCool', menuLink: '/d3-example/d3-208-interpolateCool' },
    { menuName: 'd3-209-interpolateCubehelix', menuLink: '/d3-example/d3-209-interpolateCubehelix' },
    { menuName: 'd3-210-interpolateCubehelixDefault', menuLink: '/d3-example/d3-210-interpolateCubehelixDefault' },
    { menuName: 'd3-211-interpolateCubehelixLong', menuLink: '/d3-example/d3-211-interpolateCubehelixLong' },
    { menuName: 'd3-212-interpolateDate', menuLink: '/d3-example/d3-212-interpolateDate' },
    { menuName: 'd3-213-interpolateDiscrete', menuLink: '/d3-example/d3-213-interpolateDiscrete' },
    { menuName: 'd3-214-interpolateGnBu', menuLink: '/d3-example/d3-214-interpolateGnBu' },
    { menuName: 'd3-215-interpolateGreens', menuLink: '/d3-example/d3-215-interpolateGreens' },
    { menuName: 'd3-216-interpolateGreys', menuLink: '/d3-example/d3-216-interpolateGreys' },
    { menuName: 'd3-217-interpolateHcl', menuLink: '/d3-example/d3-217-interpolateHcl' },
    { menuName: 'd3-218-interpolateHclLong', menuLink: '/d3-example/d3-218-interpolateHclLong' },
    { menuName: 'd3-219-interpolateHsl', menuLink: '/d3-example/d3-219-interpolateHsl' },
    { menuName: 'd3-220-interpolateHslLong', menuLink: '/d3-example/d3-220-interpolateHslLong' },
    { menuName: 'd3-221-interpolateHue', menuLink: '/d3-example/d3-221-interpolateHue' },
    { menuName: 'd3-222-interpolateInferno', menuLink: '/d3-example/d3-222-interpolateInferno' },
    { menuName: 'd3-223-interpolateLab', menuLink: '/d3-example/d3-223-interpolateLab' },
    { menuName: 'd3-224-interpolateMagma', menuLink: '/d3-example/d3-224-interpolateMagma' },
    { menuName: 'd3-225-interpolateNumber', menuLink: '/d3-example/d3-225-interpolateNumber' },
    { menuName: 'd3-226-interpolateNumberArray', menuLink: '/d3-example/d3-226-interpolateNumberArray' },
    { menuName: 'd3-227-interpolateObject', menuLink: '/d3-example/d3-227-interpolateObject' },
    { menuName: 'd3-228-interpolateOrRd', menuLink: '/d3-example/d3-228-interpolateOrRd' },
    { menuName: 'd3-229-interpolateOranges', menuLink: '/d3-example/d3-229-interpolateOranges' },
    { menuName: 'd3-230-interpolatePRGn', menuLink: '/d3-example/d3-230-interpolatePRGn' },
    { menuName: 'd3-231-interpolatePiYG', menuLink: '/d3-example/d3-231-interpolatePiYG' },
    { menuName: 'd3-232-interpolatePlasma', menuLink: '/d3-example/d3-232-interpolatePlasma' },
    { menuName: 'd3-233-interpolatePuBu', menuLink: '/d3-example/d3-233-interpolatePuBu' },
    { menuName: 'd3-234-interpolatePuBuGn', menuLink: '/d3-example/d3-234-interpolatePuBuGn' },
    { menuName: 'd3-235-interpolatePuOr', menuLink: '/d3-example/d3-235-interpolatePuOr' },
    { menuName: 'd3-236-interpolatePuRd', menuLink: '/d3-example/d3-236-interpolatePuRd' },
    { menuName: 'd3-237-interpolatePurples', menuLink: '/d3-example/d3-237-interpolatePurples' },
    { menuName: 'd3-238-interpolateRainbow', menuLink: '/d3-example/d3-238-interpolateRainbow' },
    { menuName: 'd3-239-interpolateRdBu', menuLink: '/d3-example/d3-239-interpolateRdBu' },
    { menuName: 'd3-240-interpolateRdGy', menuLink: '/d3-example/d3-240-interpolateRdGy' },
    { menuName: 'd3-241-interpolateRdPu', menuLink: '/d3-example/d3-241-interpolateRdPu' },
    { menuName: 'd3-242-interpolateRdYlBu', menuLink: '/d3-example/d3-242-interpolateRdYlBu' },
    { menuName: 'd3-243-interpolateRdYlGn', menuLink: '/d3-example/d3-243-interpolateRdYlGn' },
    { menuName: 'd3-244-interpolateReds', menuLink: '/d3-example/d3-244-interpolateReds' },
    { menuName: 'd3-245-interpolateRgb', menuLink: '/d3-example/d3-245-interpolateRgb' },
    { menuName: 'd3-246-interpolateRgbBasis', menuLink: '/d3-example/d3-246-interpolateRgbBasis' },
    { menuName: 'd3-247-interpolateRgbBasisClosed', menuLink: '/d3-example/d3-247-interpolateRgbBasisClosed' },
    { menuName: 'd3-248-interpolateRound', menuLink: '/d3-example/d3-248-interpolateRound' },
    { menuName: 'd3-249-interpolateSinebow', menuLink: '/d3-example/d3-249-interpolateSinebow' },
    { menuName: 'd3-250-interpolateSpectral', menuLink: '/d3-example/d3-250-interpolateSpectral' },
    { menuName: 'd3-251-interpolateString', menuLink: '/d3-example/d3-251-interpolateString' },
    { menuName: 'd3-252-interpolateTransformCss', menuLink: '/d3-example/d3-252-interpolateTransformCss' },
    { menuName: 'd3-253-interpolateTransformSvg', menuLink: '/d3-example/d3-253-interpolateTransformSvg' },
    { menuName: 'd3-254-interpolateTurbo', menuLink: '/d3-example/d3-254-interpolateTurbo' },
    { menuName: 'd3-255-interpolateViridis', menuLink: '/d3-example/d3-255-interpolateViridis' },
    { menuName: 'd3-256-interpolateWarm', menuLink: '/d3-example/d3-256-interpolateWarm' },
    { menuName: 'd3-257-interpolateYlGn', menuLink: '/d3-example/d3-257-interpolateYlGn' },
    { menuName: 'd3-258-interpolateYlGnBu', menuLink: '/d3-example/d3-258-interpolateYlGnBu' },
    { menuName: 'd3-259-interpolateYlOrBr', menuLink: '/d3-example/d3-259-interpolateYlOrBr' },
    { menuName: 'd3-260-interpolateYlOrRd', menuLink: '/d3-example/d3-260-interpolateYlOrRd' },
    { menuName: 'd3-261-interpolateZoom', menuLink: '/d3-example/d3-261-interpolateZoom' },
    { menuName: 'd3-262-interrupt', menuLink: '/d3-example/d3-262-interrupt' },
    { menuName: 'd3-263-intersection', menuLink: '/d3-example/d3-263-intersection' },
    { menuName: 'd3-264-interval', menuLink: '/d3-example/d3-264-interval' },
    { menuName: 'd3-265-isoFormat', menuLink: '/d3-example/d3-265-isoFormat' },
    { menuName: 'd3-266-isoParse', menuLink: '/d3-example/d3-266-isoParse' },
    { menuName: 'd3-267-json', menuLink: '/d3-example/d3-267-json' },
    { menuName: 'd3-268-lab', menuLink: '/d3-example/d3-268-lab' },
    { menuName: 'd3-269-lch', menuLink: '/d3-example/d3-269-lch' },
    { menuName: 'd3-270-least', menuLink: '/d3-example/d3-270-least' },
    { menuName: 'd3-271-leastIndex', menuLink: '/d3-example/d3-271-leastIndex' },
    { menuName: 'd3-272-line', menuLink: '/d3-example/d3-272-line' },
    { menuName: 'd3-273-lineRadial', menuLink: '/d3-example/d3-273-lineRadial' },
    { menuName: 'd3-274-link', menuLink: '/d3-example/d3-274-link' },
    { menuName: 'd3-275-linkHorizontal', menuLink: '/d3-example/d3-275-linkHorizontal' },
    { menuName: 'd3-276-linkRadial', menuLink: '/d3-example/d3-276-linkRadial' },
    { menuName: 'd3-277-linkVertical', menuLink: '/d3-example/d3-277-linkVertical' },
    { menuName: 'd3-278-local', menuLink: '/d3-example/d3-278-local' },
    { menuName: 'd3-279-map', menuLink: '/d3-example/d3-279-map' },
    { menuName: 'd3-280-matcher', menuLink: '/d3-example/d3-280-matcher' },
    { menuName: 'd3-281-max', menuLink: '/d3-example/d3-281-max' },
    { menuName: 'd3-282-maxIndex', menuLink: '/d3-example/d3-282-maxIndex' },
    { menuName: 'd3-283-mean', menuLink: '/d3-example/d3-283-mean' },
    { menuName: 'd3-284-median', menuLink: '/d3-example/d3-284-median' },
    { menuName: 'd3-285-merge', menuLink: '/d3-example/d3-285-merge' },
    { menuName: 'd3-286-min', menuLink: '/d3-example/d3-286-min' },
    { menuName: 'd3-287-minIndex', menuLink: '/d3-example/d3-287-minIndex' },
    { menuName: 'd3-288-mode', menuLink: '/d3-example/d3-288-mode' },
    { menuName: 'd3-289-namespace', menuLink: '/d3-example/d3-289-namespace' },
    { menuName: 'd3-290-namespaces', menuLink: '/d3-example/d3-290-namespaces' },
    { menuName: 'd3-291-nice', menuLink: '/d3-example/d3-291-nice' },
    { menuName: 'd3-292-now', menuLink: '/d3-example/d3-292-now' },
    { menuName: 'd3-293-pack', menuLink: '/d3-example/d3-293-pack' },
    { menuName: 'd3-294-packEnclose', menuLink: '/d3-example/d3-294-packEnclose' },
    { menuName: 'd3-295-packSiblings', menuLink: '/d3-example/d3-295-packSiblings' },
    { menuName: 'd3-296-pairs', menuLink: '/d3-example/d3-296-pairs' },
    { menuName: 'd3-297-partition', menuLink: '/d3-example/d3-297-partition' },
    { menuName: 'd3-298-path', menuLink: '/d3-example/d3-298-path' },
    { menuName: 'd3-299-permute', menuLink: '/d3-example/d3-299-permute' },
    { menuName: 'd3-300-pie', menuLink: '/d3-example/d3-300-pie' },
    { menuName: 'd3-301-piecewise', menuLink: '/d3-example/d3-301-piecewise' },
    { menuName: 'd3-302-pointRadial', menuLink: '/d3-example/d3-302-pointRadial' },
    { menuName: 'd3-303-pointer', menuLink: '/d3-example/d3-303-pointer' },
    { menuName: 'd3-304-pointers', menuLink: '/d3-example/d3-304-pointers' },
    { menuName: 'd3-305-polygonArea', menuLink: '/d3-example/d3-305-polygonArea' },
    { menuName: 'd3-306-polygonCentroid', menuLink: '/d3-example/d3-306-polygonCentroid' },
    { menuName: 'd3-307-polygonContains', menuLink: '/d3-example/d3-307-polygonContains' },
    { menuName: 'd3-308-polygonHull', menuLink: '/d3-example/d3-308-polygonHull' },
    { menuName: 'd3-309-polygonLength', menuLink: '/d3-example/d3-309-polygonLength' },
    { menuName: 'd3-310-precisionFixed', menuLink: '/d3-example/d3-310-precisionFixed' },
    { menuName: 'd3-311-precisionPrefix', menuLink: '/d3-example/d3-311-precisionPrefix' },
    { menuName: 'd3-312-precisionRound', menuLink: '/d3-example/d3-312-precisionRound' },
    { menuName: 'd3-313-quadtree', menuLink: '/d3-example/d3-313-quadtree' },
    { menuName: 'd3-314-quantile', menuLink: '/d3-example/d3-314-quantile' },
    { menuName: 'd3-315-quantileSorted', menuLink: '/d3-example/d3-315-quantileSorted' },
    { menuName: 'd3-316-quantize', menuLink: '/d3-example/d3-316-quantize' },
    { menuName: 'd3-317-quickselect', menuLink: '/d3-example/d3-317-quickselect' },
    { menuName: 'd3-318-randomBates', menuLink: '/d3-example/d3-318-randomBates' },
    { menuName: 'd3-319-randomBernoulli', menuLink: '/d3-example/d3-319-randomBernoulli' },
    { menuName: 'd3-320-randomBeta', menuLink: '/d3-example/d3-320-randomBeta' },
    { menuName: 'd3-321-randomBinomial', menuLink: '/d3-example/d3-321-randomBinomial' },
    { menuName: 'd3-322-randomCauchy', menuLink: '/d3-example/d3-322-randomCauchy' },
    { menuName: 'd3-323-randomExponential', menuLink: '/d3-example/d3-323-randomExponential' },
    { menuName: 'd3-324-randomGamma', menuLink: '/d3-example/d3-324-randomGamma' },
    { menuName: 'd3-325-randomGeometric', menuLink: '/d3-example/d3-325-randomGeometric' },
    { menuName: 'd3-326-randomInt', menuLink: '/d3-example/d3-326-randomInt' },
    { menuName: 'd3-327-randomIrwinHall', menuLink: '/d3-example/d3-327-randomIrwinHall' },
    { menuName: 'd3-328-randomLcg', menuLink: '/d3-example/d3-328-randomLcg' },
    { menuName: 'd3-329-randomLogNormal', menuLink: '/d3-example/d3-329-randomLogNormal' },
    { menuName: 'd3-330-randomLogistic', menuLink: '/d3-example/d3-330-randomLogistic' },
    { menuName: 'd3-331-randomNormal', menuLink: '/d3-example/d3-331-randomNormal' },
    { menuName: 'd3-332-randomPareto', menuLink: '/d3-example/d3-332-randomPareto' },
    { menuName: 'd3-333-randomPoisson', menuLink: '/d3-example/d3-333-randomPoisson' },
    { menuName: 'd3-334-randomUniform', menuLink: '/d3-example/d3-334-randomUniform' },
    { menuName: 'd3-335-randomWeibull', menuLink: '/d3-example/d3-335-randomWeibull' },
    { menuName: 'd3-336-range', menuLink: '/d3-example/d3-336-range' },
    { menuName: 'd3-337-rank', menuLink: '/d3-example/d3-337-rank' },
    { menuName: 'd3-338-reduce', menuLink: '/d3-example/d3-338-reduce' },
    { menuName: 'd3-339-reverse', menuLink: '/d3-example/d3-339-reverse' },
    { menuName: 'd3-340-rgb', menuLink: '/d3-example/d3-340-rgb' },
    { menuName: 'd3-341-ribbon', menuLink: '/d3-example/d3-341-ribbon' },
    { menuName: 'd3-342-ribbonArrow', menuLink: '/d3-example/d3-342-ribbonArrow' },
    { menuName: 'd3-343-rollup', menuLink: '/d3-example/d3-343-rollup' },
    { menuName: 'd3-344-rollups', menuLink: '/d3-example/d3-344-rollups' },
    { menuName: 'd3-345-scaleBand', menuLink: '/d3-example/d3-345-scaleBand' },
    { menuName: 'd3-346-scaleDiverging', menuLink: '/d3-example/d3-346-scaleDiverging' },
    { menuName: 'd3-347-scaleDivergingLog', menuLink: '/d3-example/d3-347-scaleDivergingLog' },
    { menuName: 'd3-348-scaleDivergingPow', menuLink: '/d3-example/d3-348-scaleDivergingPow' },
    { menuName: 'd3-349-scaleDivergingSqrt', menuLink: '/d3-example/d3-349-scaleDivergingSqrt' },
    { menuName: 'd3-350-scaleDivergingSymlog', menuLink: '/d3-example/d3-350-scaleDivergingSymlog' },
    { menuName: 'd3-351-scaleIdentity', menuLink: '/d3-example/d3-351-scaleIdentity' },
    { menuName: 'd3-352-scaleImplicit', menuLink: '/d3-example/d3-352-scaleImplicit' },
    { menuName: 'd3-353-scaleLinear', menuLink: '/d3-example/d3-353-scaleLinear' },
    { menuName: 'd3-354-scaleLog', menuLink: '/d3-example/d3-354-scaleLog' },
    { menuName: 'd3-355-scaleOrdinal', menuLink: '/d3-example/d3-355-scaleOrdinal' },
    { menuName: 'd3-356-scalePoint', menuLink: '/d3-example/d3-356-scalePoint' },
    { menuName: 'd3-357-scalePow', menuLink: '/d3-example/d3-357-scalePow' },
    { menuName: 'd3-358-scaleQuantile', menuLink: '/d3-example/d3-358-scaleQuantile' },
    { menuName: 'd3-359-scaleQuantize', menuLink: '/d3-example/d3-359-scaleQuantize' },
    { menuName: 'd3-360-scaleRadial', menuLink: '/d3-example/d3-360-scaleRadial' },
    { menuName: 'd3-361-scaleSequential', menuLink: '/d3-example/d3-361-scaleSequential' },
    { menuName: 'd3-362-scaleSequentialLog', menuLink: '/d3-example/d3-362-scaleSequentialLog' },
    { menuName: 'd3-363-scaleSequentialPow', menuLink: '/d3-example/d3-363-scaleSequentialPow' },
    { menuName: 'd3-364-scaleSequentialQuantile', menuLink: '/d3-example/d3-364-scaleSequentialQuantile' },
    { menuName: 'd3-365-scaleSequentialSqrt', menuLink: '/d3-example/d3-365-scaleSequentialSqrt' },
    { menuName: 'd3-366-scaleSequentialSymlog', menuLink: '/d3-example/d3-366-scaleSequentialSymlog' },
    { menuName: 'd3-367-scaleSqrt', menuLink: '/d3-example/d3-367-scaleSqrt' },
    { menuName: 'd3-368-scaleSymlog', menuLink: '/d3-example/d3-368-scaleSymlog' },
    { menuName: 'd3-369-scaleThreshold', menuLink: '/d3-example/d3-369-scaleThreshold' },
    { menuName: 'd3-370-scaleTime', menuLink: '/d3-example/d3-370-scaleTime' },
    { menuName: 'd3-371-scaleUtc', menuLink: '/d3-example/d3-371-scaleUtc' },
    { menuName: 'd3-372-select', menuLink: '/d3-example/d3-372-select' },
    { menuName: 'd3-373-selectAll', menuLink: '/d3-example/d3-373-selectAll' },
    { menuName: 'd3-374-selection', menuLink: '/d3-example/d3-374-selection' },
    { menuName: 'd3-375-selector', menuLink: '/d3-example/d3-375-selector' },
    { menuName: 'd3-376-selectorAll', menuLink: '/d3-example/d3-376-selectorAll' },
    { menuName: 'd3-377-shuffle', menuLink: '/d3-example/d3-377-shuffle' },
    { menuName: 'd3-378-shuffler', menuLink: '/d3-example/d3-378-shuffler' },
    { menuName: 'd3-379-some', menuLink: '/d3-example/d3-379-some' },
    { menuName: 'd3-380-sort', menuLink: '/d3-example/d3-380-sort' },
    { menuName: 'd3-381-stack', menuLink: '/d3-example/d3-381-stack' },
    { menuName: 'd3-382-stackOffsetDiverging', menuLink: '/d3-example/d3-382-stackOffsetDiverging' },
    { menuName: 'd3-383-stackOffsetExpand', menuLink: '/d3-example/d3-383-stackOffsetExpand' },
    { menuName: 'd3-384-stackOffsetNone', menuLink: '/d3-example/d3-384-stackOffsetNone' },
    { menuName: 'd3-385-stackOffsetSilhouette', menuLink: '/d3-example/d3-385-stackOffsetSilhouette' },
    { menuName: 'd3-386-stackOffsetWiggle', menuLink: '/d3-example/d3-386-stackOffsetWiggle' },
    { menuName: 'd3-387-stackOrderAppearance', menuLink: '/d3-example/d3-387-stackOrderAppearance' },
    { menuName: 'd3-388-stackOrderAscending', menuLink: '/d3-example/d3-388-stackOrderAscending' },
    { menuName: 'd3-389-stackOrderDescending', menuLink: '/d3-example/d3-389-stackOrderDescending' },
    { menuName: 'd3-390-stackOrderInsideOut', menuLink: '/d3-example/d3-390-stackOrderInsideOut' },
    { menuName: 'd3-391-stackOrderNone', menuLink: '/d3-example/d3-391-stackOrderNone' },
    { menuName: 'd3-392-stackOrderReverse', menuLink: '/d3-example/d3-392-stackOrderReverse' },
    { menuName: 'd3-393-stratify', menuLink: '/d3-example/d3-393-stratify' },
    { menuName: 'd3-394-style', menuLink: '/d3-example/d3-394-style' },
    { menuName: 'd3-395-subset', menuLink: '/d3-example/d3-395-subset' },
    { menuName: 'd3-396-sum', menuLink: '/d3-example/d3-396-sum' },
    { menuName: 'd3-397-superset', menuLink: '/d3-example/d3-397-superset' },
    { menuName: 'd3-398-svg', menuLink: '/d3-example/d3-398-svg' },
    { menuName: 'd3-399-symbol', menuLink: '/d3-example/d3-399-symbol' },
    { menuName: 'd3-400-symbolAsterisk', menuLink: '/d3-example/d3-400-symbolAsterisk' },
    { menuName: 'd3-401-symbolCircle', menuLink: '/d3-example/d3-401-symbolCircle' },
    { menuName: 'd3-402-symbolCross', menuLink: '/d3-example/d3-402-symbolCross' },
    { menuName: 'd3-403-symbolDiamond', menuLink: '/d3-example/d3-403-symbolDiamond' },
    { menuName: 'd3-404-symbolDiamond2', menuLink: '/d3-example/d3-404-symbolDiamond2' },
    { menuName: 'd3-405-symbolPlus', menuLink: '/d3-example/d3-405-symbolPlus' },
    { menuName: 'd3-406-symbolSquare', menuLink: '/d3-example/d3-406-symbolSquare' },
    { menuName: 'd3-407-symbolSquare2', menuLink: '/d3-example/d3-407-symbolSquare2' },
    { menuName: 'd3-408-symbolStar', menuLink: '/d3-example/d3-408-symbolStar' },
    { menuName: 'd3-409-symbolTriangle', menuLink: '/d3-example/d3-409-symbolTriangle' },
    { menuName: 'd3-410-symbolTriangle2', menuLink: '/d3-example/d3-410-symbolTriangle2' },
    { menuName: 'd3-411-symbolWye', menuLink: '/d3-example/d3-411-symbolWye' },
    { menuName: 'd3-412-symbolX', menuLink: '/d3-example/d3-412-symbolX' },
    { menuName: 'd3-413-symbolsFill', menuLink: '/d3-example/d3-413-symbolsFill' },
    { menuName: 'd3-414-symbolsStroke', menuLink: '/d3-example/d3-414-symbolsStroke' },
    { menuName: 'd3-415-text', menuLink: '/d3-example/d3-415-text' },
    { menuName: 'd3-416-thresholdFreedmanDiaconis', menuLink: '/d3-example/d3-416-thresholdFreedmanDiaconis' },
    { menuName: 'd3-417-thresholdScott', menuLink: '/d3-example/d3-417-thresholdScott' },
    { menuName: 'd3-418-thresholdSturges', menuLink: '/d3-example/d3-418-thresholdSturges' },
    { menuName: 'd3-419-tickFormat', menuLink: '/d3-example/d3-419-tickFormat' },
    { menuName: 'd3-420-tickIncrement', menuLink: '/d3-example/d3-420-tickIncrement' },
    { menuName: 'd3-421-tickStep', menuLink: '/d3-example/d3-421-tickStep' },
    { menuName: 'd3-422-ticks', menuLink: '/d3-example/d3-422-ticks' },
    { menuName: 'd3-423-timeDay', menuLink: '/d3-example/d3-423-timeDay' },
    { menuName: 'd3-424-timeDays', menuLink: '/d3-example/d3-424-timeDays' },
    { menuName: 'd3-425-timeFormat', menuLink: '/d3-example/d3-425-timeFormat' },
    { menuName: 'd3-426-timeFormatDefaultLocale', menuLink: '/d3-example/d3-426-timeFormatDefaultLocale' },
    { menuName: 'd3-427-timeFormatLocale', menuLink: '/d3-example/d3-427-timeFormatLocale' },
    { menuName: 'd3-428-timeFriday', menuLink: '/d3-example/d3-428-timeFriday' },
    { menuName: 'd3-429-timeFridays', menuLink: '/d3-example/d3-429-timeFridays' },
    { menuName: 'd3-430-timeHour', menuLink: '/d3-example/d3-430-timeHour' },
    { menuName: 'd3-431-timeHours', menuLink: '/d3-example/d3-431-timeHours' },
    { menuName: 'd3-432-timeInterval', menuLink: '/d3-example/d3-432-timeInterval' },
    { menuName: 'd3-433-timeMillisecond', menuLink: '/d3-example/d3-433-timeMillisecond' },
    { menuName: 'd3-434-timeMilliseconds', menuLink: '/d3-example/d3-434-timeMilliseconds' },
    { menuName: 'd3-435-timeMinute', menuLink: '/d3-example/d3-435-timeMinute' },
    { menuName: 'd3-436-timeMinutes', menuLink: '/d3-example/d3-436-timeMinutes' },
    { menuName: 'd3-437-timeMonday', menuLink: '/d3-example/d3-437-timeMonday' },
    { menuName: 'd3-438-timeMondays', menuLink: '/d3-example/d3-438-timeMondays' },
    { menuName: 'd3-439-timeMonth', menuLink: '/d3-example/d3-439-timeMonth' },
    { menuName: 'd3-440-timeMonths', menuLink: '/d3-example/d3-440-timeMonths' },
    { menuName: 'd3-441-timeParse', menuLink: '/d3-example/d3-441-timeParse' },
    { menuName: 'd3-442-timeSaturday', menuLink: '/d3-example/d3-442-timeSaturday' },
    { menuName: 'd3-443-timeSaturdays', menuLink: '/d3-example/d3-443-timeSaturdays' },
    { menuName: 'd3-444-timeSecond', menuLink: '/d3-example/d3-444-timeSecond' },
    { menuName: 'd3-445-timeSeconds', menuLink: '/d3-example/d3-445-timeSeconds' },
    { menuName: 'd3-446-timeSunday', menuLink: '/d3-example/d3-446-timeSunday' },
    { menuName: 'd3-447-timeSundays', menuLink: '/d3-example/d3-447-timeSundays' },
    { menuName: 'd3-448-timeThursday', menuLink: '/d3-example/d3-448-timeThursday' },
    { menuName: 'd3-449-timeThursdays', menuLink: '/d3-example/d3-449-timeThursdays' },
    { menuName: 'd3-450-timeTickInterval', menuLink: '/d3-example/d3-450-timeTickInterval' },
    { menuName: 'd3-451-timeTicks', menuLink: '/d3-example/d3-451-timeTicks' },
    { menuName: 'd3-452-timeTuesday', menuLink: '/d3-example/d3-452-timeTuesday' },
    { menuName: 'd3-453-timeTuesdays', menuLink: '/d3-example/d3-453-timeTuesdays' },
    { menuName: 'd3-454-timeWednesday', menuLink: '/d3-example/d3-454-timeWednesday' },
    { menuName: 'd3-455-timeWednesdays', menuLink: '/d3-example/d3-455-timeWednesdays' },
    { menuName: 'd3-456-timeWeek', menuLink: '/d3-example/d3-456-timeWeek' },
    { menuName: 'd3-457-timeWeeks', menuLink: '/d3-example/d3-457-timeWeeks' },
    { menuName: 'd3-458-timeYear', menuLink: '/d3-example/d3-458-timeYear' },
    { menuName: 'd3-459-timeYears', menuLink: '/d3-example/d3-459-timeYears' },
    { menuName: 'd3-460-timeout', menuLink: '/d3-example/d3-460-timeout' },
    { menuName: 'd3-461-timer', menuLink: '/d3-example/d3-461-timer' },
    { menuName: 'd3-462-timerFlush', menuLink: '/d3-example/d3-462-timerFlush' },
    { menuName: 'd3-463-transition', menuLink: '/d3-example/d3-463-transition' },
    { menuName: 'd3-464-transpose', menuLink: '/d3-example/d3-464-transpose' },
    { menuName: 'd3-465-tree', menuLink: '/d3-example/d3-465-tree' },
    { menuName: 'd3-466-treemap', menuLink: '/d3-example/d3-466-treemap' },
    { menuName: 'd3-467-treemapBinary', menuLink: '/d3-example/d3-467-treemapBinary' },
    { menuName: 'd3-468-treemapDice', menuLink: '/d3-example/d3-468-treemapDice' },
    { menuName: 'd3-469-treemapResquarify', menuLink: '/d3-example/d3-469-treemapResquarify' },
    { menuName: 'd3-470-treemapSlice', menuLink: '/d3-example/d3-470-treemapSlice' },
    { menuName: 'd3-471-treemapSliceDice', menuLink: '/d3-example/d3-471-treemapSliceDice' },
    { menuName: 'd3-472-treemapSquarify', menuLink: '/d3-example/d3-472-treemapSquarify' },
    { menuName: 'd3-473-tsv', menuLink: '/d3-example/d3-473-tsv' },
    { menuName: 'd3-474-tsvFormat', menuLink: '/d3-example/d3-474-tsvFormat' },
    { menuName: 'd3-475-tsvFormatBody', menuLink: '/d3-example/d3-475-tsvFormatBody' },
    { menuName: 'd3-476-tsvFormatRow', menuLink: '/d3-example/d3-476-tsvFormatRow' },
    { menuName: 'd3-477-tsvFormatRows', menuLink: '/d3-example/d3-477-tsvFormatRows' },
    { menuName: 'd3-478-tsvFormatValue', menuLink: '/d3-example/d3-478-tsvFormatValue' },
    { menuName: 'd3-479-tsvParse', menuLink: '/d3-example/d3-479-tsvParse' },
    { menuName: 'd3-480-tsvParseRows', menuLink: '/d3-example/d3-480-tsvParseRows' },
    { menuName: 'd3-481-union', menuLink: '/d3-example/d3-481-union' },
    { menuName: 'd3-482-utcDay', menuLink: '/d3-example/d3-482-utcDay' },
    { menuName: 'd3-483-utcDays', menuLink: '/d3-example/d3-483-utcDays' },
    { menuName: 'd3-484-utcFormat', menuLink: '/d3-example/d3-484-utcFormat' },
    { menuName: 'd3-485-utcFriday', menuLink: '/d3-example/d3-485-utcFriday' },
    { menuName: 'd3-486-utcFridays', menuLink: '/d3-example/d3-486-utcFridays' },
    { menuName: 'd3-487-utcHour', menuLink: '/d3-example/d3-487-utcHour' },
    { menuName: 'd3-488-utcHours', menuLink: '/d3-example/d3-488-utcHours' },
    { menuName: 'd3-489-utcMillisecond', menuLink: '/d3-example/d3-489-utcMillisecond' },
    { menuName: 'd3-490-utcMilliseconds', menuLink: '/d3-example/d3-490-utcMilliseconds' },
    { menuName: 'd3-491-utcMinute', menuLink: '/d3-example/d3-491-utcMinute' },
    { menuName: 'd3-492-utcMinutes', menuLink: '/d3-example/d3-492-utcMinutes' },
    { menuName: 'd3-493-utcMonday', menuLink: '/d3-example/d3-493-utcMonday' },
    { menuName: 'd3-494-utcMondays', menuLink: '/d3-example/d3-494-utcMondays' },
    { menuName: 'd3-495-utcMonth', menuLink: '/d3-example/d3-495-utcMonth' },
    
  ]);
  

  useEffect(() => {
    setTimeout(() => {
      setIsActiveTransition(true);
    }, 300);
  }, []);

  const menuItemClick = useCallback((item: ISideBar.MenuItem) => {
    router.push(item.menuLink);
  }, [router]);

  const mobileSideBarBackgroundClick = useCallback(() => {
    setCommonLayoutModeState('mobile-basic');
  }, [setCommonLayoutModeState]);

  const isMenuActive = useCallback((item: ISideBar.MenuItem) => {
    const asPath = pathname;
    const isActive = asPath?.includes(item.menuLink);
    if (isActive && typeof document !== 'undefined') {
      const offsetTop = document.querySelector<HTMLElement>('.ul-menu-list')?.querySelector<HTMLElement>(`li[data-value=${item.menuName}]`)?.offsetTop;
      if (typeof offsetTop === 'number') {
        if (sideBarElementRef.current !== null) {
          // sideBarElementRef.current.scrollTop = offsetTop;
          anime({
            targets: [sideBarElementRef.current],
            scrollTop: offsetTop - 140,
            easing: 'easeOutQuint',
            duration: 400,
          });
        }
      }
    }
    return isActive;
  }, [pathname]);

  return (
    <>
      <div 
        className={[
          styles['side-bar-background'],
          styles[commonLayoutModeState],
          isActiveTransition ? styles['animation-duration'] : '',
        ].join(' ')}
        onClick={mobileSideBarBackgroundClick}></div>
      <div 
        ref={sideBarElementRef}
        className={[
          styles['side-bar'],
          styles[commonLayoutModeState],
          isActiveTransition ? styles['animation-duration'] : '',
        ].join(' ')}>
        <ul className={[
            'ul-menu-list',
            styles['menu-list']
          ].join(' ')}>
          {
            menuItems.map((item, index) => {
              return (
                <li 
                  key={index} 
                  className={[
                    styles['item'],
                    isMenuActive(item) ? styles['active'] : '',
                  ].join(' ')}
                  data-value={item.menuName}
                  onClick={e => menuItemClick(item)}>
                  { item.menuName }
                </li>
              )
            })
          }
        </ul>
      </div>
    </>
  );
};

export default SideBar;